---
kind: "ReplicationController"
apiVersion: "v1"
metadata:
  name: demo-1.0.0
  labels:
    name: demo
    version: 1.0.0
spec:
  replicas: 2
  selector:
    name: demo
    version: 1.0.0
  template:
    metadata:
      labels:
        name: demo
        version: 1.0.0
    spec:
      containers:
        - name: "demo"
          image: "gcr.io/parkster-env-stughelg/kubernetes-presentation:1.0.0"
          livenessProbe:
            httpGet:
              path: /
              port: external
            initialDelaySeconds: 30
            timeoutSeconds: 1
          ports:
            - containerPort: 3000
              name: external
              protocol: "TCP"